### PR TITLE
hee merge if u want

### PR DESCRIPTION
**Pull request by Achu2234**

### CODE REVIEW

**Comment by notPlasticCat** [comment]
Hey, @Achu2234 , thanks for the pull request :D
For now, I have to write my college assignments 😢 
I'll review it tomorrow and merge it.

**Comment by raveen2k3** [comment]
Pro ppls everywhere

**Comment by Achu2234** [comment]
> Pro ppls everywhere

who

**Comment by raveen2k3** [comment]
You and aadhavan 🥲

**Comment by Achu2234** [comment]
> You and aadhavan 🥲
me noob

**Review by notPlasticCat — APPROVED** [review]

**Pull request merged**
